### ISSUE TITLE
您好，这个语法看不懂……

### ISSUE THREAD

**Issue by Solodye** [zhidanfeng/WPF.UI#1]
var source =
                $"pack://application:,,,/WPF.UI;component/Themes/Theme.{(IsDarkTheme ? "Dark" : "Light")}.xaml";

项目没办法运行，k，开发者能解释一下这个$是怎么来的嘛？
还有您博客园上面http://www.cnblogs.com/zhidanfeng/p/6920719.html
的代码一直显示命名空间clr-namespace:ZdfFlatUI不存在Timeline和TimelineItem名称

**Comment by sunnypaine** [comment]
吱吱，可以哦，wpf研究得很溜啊。~~

**Comment by zhidanfeng** [comment]
最新版已经修复
