### ISSUE TITLE
大佬 我有一个NavigateMenu的问题

### ISSUE THREAD

**Issue by yanjinhuagood** [zhidanfeng/WPF.UI#2]
我将ZExpander style 加了一个
 <ContentPresenter IsHitTestVisible="True" Content="{TemplateBinding Tag}"
 VerticalAlignment="Center" Margin="0,0,20,0"/>

<WPF.UI:ZExpander.Tag>
   <Button x:Name="tbAdd" Width="20" Height="20" Content="+" Visibility=“”>
  </Button>
</WPF.UI:ZExpander.Tag>

![image](https://user-images.githubusercontent.com/23089734/41499553-86e24a50-71b4-11e8-9dee-3761021a4dae.png)

我怎么控制“+”隐藏或显示呢

**Comment by yanjinhuagood** [comment]
<ContentPresenter IsHitTestVisible="True" Content="{TemplateBinding Tag}"
 VerticalAlignment="Center" Margin="0,0,20,0"/>


<WPF.UI:ZExpander.Tag>
   <Button x:Name="tbAdd" Width="20" Height="20" Content="+" Visibility>
  </Button>
</WPF.UI:YExpander.Tag>

**Comment by yanjinhuagood** [comment]
![image](https://user-images.githubusercontent.com/23089734/41499611-3f3a1aec-71b5-11e8-8ca9-1864dd56e1ed.png)

**Comment by zhidanfeng** [comment]
你想什么情况下显示，什么情况下隐藏呢

**Comment by yanjinhuagood** [comment]
ZExpander的Header不等于2323的都隐藏。

**Comment by yanjinhuagood** [comment]
我看了源码发现 ZExpander的Header 等于{binding Path=Name}  我一直没有找到这个Name在哪里赋值的。谢谢大佬的解答。

**Comment by zhidanfeng** [comment]
这个是列表分组GroupBy后的属性，不是我们自己定义的

**Comment by yanjinhuagood** [comment]
好吧。 那大佬能实现“+”号可显示或者不显示么

**Comment by yanjinhuagood** [comment]
大佬你咋关闭了
