### ISSUE TITLE
这么好的库是不维护了吗？

### ISSUE THREAD

**Issue by NaBian** [zhidanfeng/WPF.UI#4]

**Comment by zhidanfeng** [comment]
谢谢，目前已经没有维护了，后面如果有改动还是会提交代码的

**Comment by NaBian** [comment]
@zhidanfeng 诚邀您加入我们的QQ群：714704041，希望能一起讨论技术 😆

**Comment by QQWE1345** [comment]
最近有发表博客啥的么 我想关注下😆

**Comment by zhidanfeng** [comment]
> 最近有发表博客啥的么 我想关注下

好久没写博客了……

**Comment by NaBian** [comment]
@zhidanfeng 大佬有qq吗，邀请你呀
